### ISSUE TITLE
Tracking Camera related Event Generation and Trigger Source

### ISSUE THREAD

**Issue by empbarney** [missioncommand/emp3-android#114]
BLUF: Strategy of adding a "TAG" argument to "setCamera" or "apply" methods will NOT work.

Changing Camera causes a number of events, but those events are triggered by the WW Navigator and are decoupled from the API actions. Events NAVIGATOR_MOVED and NAVIGATOR_STOPPED are generated by WW when Camera is moved (either by user actions on the screen or as a result of Camera Movement by the application). Additionally Camera movement action is executed on a UI thread and application is most probably not on UI thread when API is invoked.

So we will NOT be able to correlate the application API action with the event.  Any mechanism we devise will be complicated and prone to errors.

Container Event Listener: When you make the change here, you will need to put some check around it as we raise the event in a "finally" block which is executed even if API call fails for some reason.

**Comment by Ish-rivera** [comment]
The user context object should be added to the camera and lookAt apply and the map set API. The camera / lookAt apply should fire and camera / lookAt event handlers event if they are not the current camera or lookat on any map.

Initially the user context provided in the map set calls will not be processed.
The on view change event in the core should not generate camera / look at events.

**Comment by empbarney** [comment]
How about setCamera and setLookAt? When a Camera becomes map camera?

**Comment by ee11cbb19052e40b07aac0ca060c23ee** [comment]
Some more information, which may already be obvious..

Looks like there are a two ways of registering for Camera events.

1) CameraEvent listeners added to a Camera instance: camera.addCameraEventListener(...);
2) CameraEvent listeners added to a Map instance: map.addCameraEventListener(...);

When invoking `camera.apply()`:
* For the first case, it looks straightforward to support passing a _userContext_ object via an overloaded _apply_ method. Is it worth doing?
* For the second case, which is where I think you noticed an issue, it is a _ViewChangeEvent_ which will ultimately generate the CameraEvent to notify listeners who registered via the Map instance. The core of the issue is that the _ViewChangeEvent_ gets fired only after the following method call into the WW API, which does not allow us to supply a _userContext_ object: [Emp3NavigationListener.this.ww.requestRedraw();](https://github.com/missioncommand/emp3-android/blob/development/mapengine/worldwind/apk/src/main/java/mil/emp3/worldwind/Emp3NavigationListener.java#L359).

**Comment by rsupnekar** [comment]
I added user context object previously.  Unit tests were completed with issue #328 and the changes will be built with version v3.1.0.
