### ISSUE TITLE
Test Task Tactical Graphics

### ISSUE THREAD

**Issue by Ish-rivera** [missioncommand/emp3-android#177]
Test drawing editing and renderering of the following MilStd tactical graphics in development.

- [ ] Block                 => TACTICAL GRAPHICS / TASKS / BLOCK

- [ ] Clear                 => TACTICAL GRAPHICS / TASKS / CLEAR

- [ ] Ambush                => TACTICAL GRAPHICS / COMMAND AND CONTROL AND GENERAL MANEUVER / SPECIAL / LINE / AMBUSH

- [ ] Secure                => TACTICAL GRAPHICS / TASKS / SECURE

**Comment by empbarney** [comment]
![task-block-device-2017-04-19-090522](https://cloud.githubusercontent.com/assets/25461029/25181419/7c268068-24df-11e7-8d97-bb6425194fc8.png)

TASK-BLOCk

**Comment by empbarney** [comment]
![task-clear-device-2017-04-19-090807](https://cloud.githubusercontent.com/assets/25461029/25181520/d0578542-24df-11e7-982d-39feb2c34869.png)
TASK-CLEAR

**Comment by empbarney** [comment]
![ambush-device-2017-04-19-091123](https://cloud.githubusercontent.com/assets/25461029/25181660/3fb8f3da-24e0-11e7-9efc-f72e9b63a170.png)
Ambush

**Comment by empbarney** [comment]
![secure-device-2017-04-19-091405](https://cloud.githubusercontent.com/assets/25461029/25181779/9faf35c4-24e0-11e7-81d9-3cb29d923a31.png)
Secure

**Comment by empbarney** [comment]
![draw-edit-block-device-2017-04-19-094431](https://cloud.githubusercontent.com/assets/25461029/25183202/e3f076ea-24e4-11e7-8d2f-c20293fff51b.png)
Draw-Edit-Block

**Comment by empbarney** [comment]
![secure-tilted-device-2017-04-19-110532](https://cloud.githubusercontent.com/assets/25461029/25187141/2bf8c93c-24f0-11e7-8355-7b20ad7dca88.png)
Secure-tilted-camera

**Comment by empbarney** [comment]
![ambush-tilted-device-2017-04-19-110648](https://cloud.githubusercontent.com/assets/25461029/25187215/5cb34dcc-24f0-11e7-83cc-90270b0c3679.png)
Ambush-Tilted

**Comment by empbarney** [comment]
Test Instructions:
Branch : feature/emp3-android#177-Tactical-Graphic-Testing
Build and install Capability Tester.

Run the Basic Shapes Editor test.
"Add IDrawEventListener" from the "..." menu.
"Set Stroke Style" for "..." menu so that you can clearly see what is drawn on the map.

Now zoom in so that view is filled with the US map.
1. Now "Draw Shape" each of the Tactical Graphics features described at the beginning of the ticket.
save each shape on the map by choosing "Completing".
2. Now use the "Edit Shape" button to edit each feature. (You do that by selecting the same items in the popup that is used to create the feature).

Now set the Camera as follows: 33.348, -102.839, 135234, -14.649, 63.515, 0 (Object is to see the horizon).  Now repeat steps 1 and 2 described above.

**Comment by mubinakhan** [comment]
![screenshot_20170419-171205 1](https://cloud.githubusercontent.com/assets/25485443/25202369/215df816-2523-11e7-87ee-b9e06e75744f.png)

**Comment by mubinakhan** [comment]
Need to verify

**Comment by empbarney** [comment]
If you still have the build, can you also try the CBRN group?

Tactical Graphics -> Mobility/Survivalibility -> Nuclear, Biological, and Chemical -> Everything under this.
 I found a couple of issues and created Issue #187 that still needs to be fixed.

**Comment by mubinakhan** [comment]
![screenshot_20170420-103244 1](https://cloud.githubusercontent.com/assets/25485443/25235934/903ab1ca-25b4-11e7-8c00-0c07b9048fa7.png)

**Comment by mubinakhan** [comment]
Reintegrate
