### ISSUE TITLE
TACGRP.MOBSU.OBST.ATO.ATDATM 	 ANTITANK DITCH REINFORCED WITH ANTITANK MINES	is incorrect

### ISSUE THREAD

**Issue by empbarney** [missioncommand/emp3-android#197]
![atdatm_document](https://cloud.githubusercontent.com/assets/25461029/25235472/338bf2e6-25b3-11e7-8b57-00842b7cc553.png)
![atdatm-device-2017-04-20-102210](https://cloud.githubusercontent.com/assets/25461029/25235495/47b4f510-25b3-11e7-86fc-ecaf26946346.png)

**Comment by Ish-rivera** [comment]
At this altitude the renderer may not generate detail. However at 100K altitude there is, But in Test-Basic the detail only shows while selected.

**Comment by rsupnekar** [comment]
It works correctly in test-basic.  In test-vandv it is hard to draw this close to the ground because we need to give lat, long manually.  This is not an issue.

![screenshot from 2017-06-14 10-43-27](https://user-images.githubusercontent.com/25460036/27138384-5f931700-50ee-11e7-907e-5d6b880ce4fa.png)

**Comment by michael-spinelli** [comment]
Safe to label as not a bug then?

**Comment by rsupnekar** [comment]
Yes, I would like to close #196 and #197
