### ISSUE TITLE
Event not fired when plotting points for certain symbols

### ISSUE THREAD

**Issue by rlee-rii** [missioncommand/emp3-android#302]
When the map is in draw mode, the IDrawEventListener.onDrawUpdate() listener is not called when plotting points for certain symbols. If a point is moved while the map is in draw mode, the event will fire, however, simply plotting a point does not fire this event. Below is a partial list of symbols which exhibits this behavior.

`GFM*BCF---****X Ferry`
`GFF*LTF---****X Final Protective Fire`
`GFM*OEF---****X Fix (Obstacle Effect)`
`GFT*F-----****X Fix Task`
`GFT*A-----****X Follow and Assume`
`GFT*AS----****X Follow and Support`

**Comment by rsupnekar** [comment]
That's right.  In other words, I don't understand what the expectation here is.  Let's say you are drawing the first item in the list: Ferry.  It is a two-point graphic.  When you start, it lets you put the two points anywhere.  When you update, you can move either of those points, and the update event fires properly.  If you click elsewhere, no event fires, because it won't let you add a third point.  Are you expecting that the click will move one of the original points to the new location?

**Comment by rlee-rii** [comment]
Even on the initial two points for Ferry, the update event will not fire when those two points are plotted, only when they are moved. For other graphics, the update event fires both when the initial point is plotted and when it is moved.

**Comment by rsupnekar** [comment]
That makes more sense.  As I look through the code, I am wondering if you get an event if you delete it.  Could you test that.

**Comment by rlee-rii** [comment]
For area graphics or multiline segments where I am able to delete points, the update event does fire when points are deleted. For Ferry, I was unable to delete any points.

**Comment by rsupnekar** [comment]
That may be ok, because it has exactly two points and you can move either to change the graphic.
I have now fixed your original issue of firing the event when a point is added.  The fix will be in version 3.0.2-SNAPSHOT.
