### ISSUE TITLE
NASA WW Is not generating a View Change event after the Map READY.

### ISSUE THREAD

**Issue by Ish-rivera** [missioncommand/emp3-android#57]
When WW starts up is is not generating a view change event after the map ready is generated.

**Comment by empbarney** [comment]
I am not sure if you had noticed, If application didn't set the Camera on receiving MAP_READY then for the first operation WW throws an exception. That was happening because:

WW has a default camera lat/long etc set. We then used to override that with a Camera that had everything including Altitude set to 0. That was causing the exception. I have fixed that by syncing the camera in core with camera in Engine on MAP_READY. I have also added the code to calculate the bounds internally before generating MAP_READY.

Given all this do you still want to generate View Change after the MAP_READY is fired? 

My opinion is there is no need. Let me know if you have a specific scenario where this would be required. Applications should be able to use MAP_READY to initialize whatever they need to.
